POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXI0QGdtYWlsLmNvbSIsImV4cCI6MTcyODczNDgzMywidXNlcklkIjoyfQ.ZMEqJzHDUnw9-8hRi-wRasWNwrEgsassCqvu5Y1sTIw

{
  "name":"Test Event 1",
  "description":"A test Event 1",
  "location":"A test location 1",
  "dateTime":"2025-01-01T15:30:00.000Z"
}